apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse-vikasa
    type: grafana-clickhouse-datasource
    access: proxy
    url: clickhouse:9000
    isDefault: true
    jsonData:
      defaultDatabase: vikasa_mardot
      protocol: native
      port: 9000
      host: clickhouse
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
