#!/usr/bin/env python3
"""Generate a scaled fleet.yaml: 33 cabinets/DOT (99 total). MARDOT is shaped
into two real Atlanta corridors — a string of stations along I-85 (the
perception corridor) and the I-75 South Metro Express Lanes (reversible) —
plus scattered arterials. VELDOT/SABDOT stay a metro spread with one I-85 hero.
Deterministic (no RNG). Re-run to change the fleet, then `make gen-compose`."""

HEADER = """# fleet.yaml is the SSOT for the demo fleet's identity data — 3 DOTs, 33
# cabinets each (99 total). MARDOT is shaped into real Atlanta corridors: a
# string of stations along I-85 (route: i85 — the perception corridor) and the
# I-75 South Metro Express Lanes (route: i75s, one reversible controller),
# plus scattered arterials (route: ""). Each DOT has exactly ONE `corridor:
# i85` hero cabinet (the federation-shared / WAN-cut one); `route` is the
# physical roadway a cabinet sits on, used for corridor views. Hero cabinets
# get a private net + exporter + volume; non-hero cabinets are leaf+sim on the
# shared "vikasa" network (see tools/gen-compose composeCabinet.Hero).
# GENERATED by tools/genfleet.py — re-run it rather than hand-editing, then
# `make gen-compose`.
region: us-southeast
dots:"""

def cab(cid, vendor, lat, lon, seed, vph, route="", corridor="", expose=False, reversible=False):
    return dict(id=cid, vendor=vendor, lat=round(lat, 4), lon=round(lon, 4),
                seed=seed, base_vph=vph, route=route, corridor=corridor,
                expose=expose, reversible=reversible)

def lerp(a, b, t):
    return a + (b - a) * t

def vendor_for(i):
    return "econolite" if (i * 7) % 20 < 11 else "mccain"  # ~55% econolite

# --- MARDOT: I-85 corridor + I-75 South express lanes + arterials -------------
# Real interchange coordinates that trace the ACTUAL highway alignment (not a
# straight line): I-85 curves SW(Newnan) -> Downtown Connector -> NE(Gwinnett),
# I-75 South follows the reversible express-lane segment SE toward McDonough.
def build_mardot():
    out = []
    # I-85 stations sampled from the ACTUAL I-85 motorway centerline
    # (OpenStreetMap ref=I 85 geometry, incl. the downtown I-75/I-85
    # Connector), SW -> NE. cab-i85-001 (hero) sits on the connector through
    # Midtown Atlanta. (id, lat, lon, landmark)
    i85 = [
        ("cab-i85-002", 33.4191, -84.7297),  # Newnan
        ("cab-i85-003", 33.5203, -84.6244),  # Palmetto / Fairburn
        ("cab-i85-004", 33.6096, -84.4864),  # Union City / Camp Creek
        ("cab-i85-005", 33.6900, -84.4005),  # East Point
        ("cab-i85-001", 33.7891, -84.3916),  # Midtown / Downtown Connector (HERO)
        ("cab-i85-006", 33.8299, -84.3411),  # Lindbergh / Buckhead
        ("cab-i85-007", 33.8702, -84.2821),  # Brookhaven
        ("cab-i85-008", 33.9101, -84.2210),  # Chamblee / Doraville
        ("cab-i85-009", 33.9500, -84.1350),  # Norcross
        ("cab-i85-010", 34.0001, -84.0749),  # Duluth
    ]
    for i, (cid, lat, lon) in enumerate(i85):
        if cid == "cab-i85-001":
            out.append(cab(cid, "econolite", lat, lon, 101, 950, route="i85", corridor="i85"))
        else:
            out.append(cab(cid, vendor_for(i), lat, lon, 110 + i, 600 + (i * 53) % 400, route="i85"))

    # I-75 South Metro Express Lanes, N -> S along the reversible
    # barrier-separated segment. Coordinates are sampled from the ACTUAL I-75
    # motorway centerline (OpenStreetMap `ref=I 75` geometry) so the stations
    # sit on the real interstate. cab-i75s-01 (Stockbridge/SR-138) is the
    # reversible controller.
    i75s = [
        ("cab-i75s-02", 33.5933, -84.3866),  # I-75 @ Forest Park / Morrow
        ("cab-i75s-03", 33.5770, -84.3433),  # I-75 @ SR-54 (Jonesboro Rd)
        ("cab-i75s-01", 33.5504, -84.2874),  # I-75 @ Stockbridge (SR-138) — REVERSIBLE
        ("cab-i75s-04", 33.5166, -84.2438),  # I-75 @ Hudson Bridge Rd
        ("cab-i75s-05", 33.4563, -84.2069),  # I-75 @ McDonough (SR-20)
    ]
    for j, (cid, lat, lon) in enumerate(i75s):
        out.append(cab(cid, "econolite" if j % 2 == 0 else "mccain", lat, lon,
                       150 + j, 800 + (j * 40), route="i75s", reversible=(cid == "cab-i75s-01")))

    # arterials (route ""): cab-002 (tour fault cabinet, expose) + cab-003 +
    # a scatter around metro Atlanta to fill to 33.
    out.append(cab("cab-002", "econolite", 33.749, -84.388, 102, 600, expose=True))
    out.append(cab("cab-003", "mccain", 33.789, -84.384, 103, 500))
    n_art = 33 - len(out)
    for k in range(n_art):
        frac = k / max(1, n_art - 1)
        lat = 33.70 + 0.30 * frac + ((k % 5) - 2) * 0.02
        lon = -84.50 + 0.30 * frac - ((k % 3) - 1) * 0.02
        out.append(cab(f"cab-0{20 + k:02d}", vendor_for(k), lat, lon,
                       1300 + k, 300 + (k * 137) % 500))
    return out

# --- VELDOT / SABDOT: metro spread with one I-85 hero ------------------------
def build_spread(dot_prefix, hero_id, hero_vendor, hero_lat, hero_lon, hero_seed,
                 fixed, lat0, lon0, dlat, dlon, seed_base):
    out = [cab(hero_id, hero_vendor, hero_lat, hero_lon, hero_seed, 800,
               route="i85", corridor="i85")]
    for f in fixed:
        out.append(f)
    n_gen = 33 - len(out)
    start = dot_prefix + 4
    for i in range(n_gen):
        frac = i / max(1, n_gen - 1)
        jitter = ((i % 5) - 2) * 0.012
        lat = lat0 + dlat * frac + jitter
        lon = lon0 + dlon * frac - jitter
        out.append(cab(f"cab-{start + i:03d}", vendor_for(i), lat, lon,
                       seed_base + i, 300 + (i * 137) % 600))
    return out

DOTS = [
    {"dot": "mardot", "district": "d1", "cabinets": build_mardot()},
    {"dot": "veldot", "district": "d1", "cabinets": build_spread(
        100, "cab-i85-101", "mccain", 35.227, -80.843, 201,
        [cab("cab-102", "econolite", 35.213, -80.830, 202, 550),
         cab("cab-103", "mccain", 35.240, -80.860, 203, 450)],
        35.05, -81.10, 0.40, 0.50, 1100)},
    {"dot": "sabdot", "district": "d1", "cabinets": build_spread(
        200, "cab-i85-201", "econolite", 34.852, -82.394, 301,
        [cab("cab-202", "mccain", 34.840, -82.380, 302, 500),
         cab("cab-203", "econolite", 34.865, -82.410, 303, 400)],
        34.70, -82.62, 0.30, 0.46, 1200)},
]

def fmt(c):
    corridor = 'i85' if c.get("corridor") else '""'
    route = c["route"] if c["route"] else '""'
    flags = ''
    if c.get("expose"):
        flags += ', expose: true'
    if c.get("reversible"):
        flags += ', reversible: true'
    return (f'      - {{ id: {c["id"]+",":<13} vendor: {c["vendor"]+",":<11} '
            f'corridor: {corridor+",":<6} route: {route+",":<7} '
            f'lat: {c["lat"]:.4f}, lon: {c["lon"]:.4f}, seed: {c["seed"]}, '
            f'base_vph: {c["base_vph"]}{flags} }}')

lines = [HEADER]
for d in DOTS:
    lines.append(f'  - dot: {d["dot"]}')
    lines.append(f'    district: {d["district"]}')
    lines.append('    cabinets:')
    for c in d["cabinets"]:
        lines.append(fmt(c))

out = "\n".join(lines) + "\n"
with open("deploy/topology/fleet.yaml", "w") as f:
    f.write(out)

import collections
for d in DOTS:
    rc = collections.Counter(c["route"] or "arterial" for c in d["cabinets"])
    print(f'{d["dot"]}: {len(d["cabinets"])} cabinets, routes={dict(rc)}')
print("total:", sum(len(d["cabinets"]) for d in DOTS))
